# Generated by Django 6.0.2 on 2026-04-05 17:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тарифа')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена (₸)')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за км (₸)')),
                ('icon', models.CharField(default='fas fa-car', help_text='Иконка FontAwesome', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Отчество')),
                ('iin', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ИИН')),
                ('phone', models.CharField(default='', max_length=15, verbose_name='Телефон')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Стаж (лет)')),
                ('category', models.CharField(default='B', max_length=10, verbose_name='Категория прав')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_a', models.CharField(max_length=255, verbose_name='Точка А')),
                ('point_b', models.CharField(max_length=255, verbose_name='Точка Б')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Новый', max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_orders', to=settings.AUTH_USER_MODEL)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxi.tariff')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_reviews', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='taxi.order')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('plate_number', models.CharField(max_length=15, unique=True, verbose_name='Госномер')),
                ('status', models.CharField(choices=[('active', 'На линии'), ('service', 'В ремонте'), ('free', 'Свободна')], default='free', max_length=20, verbose_name='Статус авто')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='taxi.driver', verbose_name='Текущий водитель')),
                ('car_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxi.tariff', verbose_name='Класс/Тариф')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
