# Generated by Django 6.0.2 on 2026-03-14 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('plate_number', models.CharField(max_length=15, unique=True, verbose_name='Госномер')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('car_class', models.CharField(choices=[('econom', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес')], max_length=20, verbose_name='Класс')),
                ('status', models.CharField(default='Свободен', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='ИИН')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('experience', models.PositiveIntegerField(verbose_name='Стаж (лет)')),
                ('category', models.CharField(max_length=10, verbose_name='Категория прав')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за км')),
                ('min_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Мин. стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('point_a', models.CharField(max_length=255, verbose_name='Точка А')),
                ('point_b', models.CharField(max_length=255, verbose_name='Точка Б')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('status', models.CharField(default='Новый', max_length=50, verbose_name='Статус')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxi.tariff', verbose_name='Тариф')),
            ],
        ),
    ]
