# Generated by Django 6.0.2 on 2026-03-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_order_client_order_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='min_cost',
        ),
        migrations.AddField(
            model_name='tariff',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Базовая цена (₸)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='icon',
            field=models.CharField(default='fas fa-car', help_text='Иконка FontAwesome', max_length=50),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название тарифа'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за км (₸)'),
        ),
    ]
