# Generated by Django 6.0.2 on 2026-03-29 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_driver_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='category',
            field=models.CharField(default='B', max_length=10, verbose_name='Категория прав'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Стаж (лет)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
