# Generated by Django 6.0.2 on 2026-03-29 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_alter_driver_category_alter_driver_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='taxi.driver', verbose_name='Текущий водитель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxi.tariff', verbose_name='Класс/Тариф'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('active', 'На линии'), ('service', 'В ремонте'), ('free', 'Свободна')], default='free', max_length=20, verbose_name='Статус авто'),
        ),
    ]
